# Generated by Django 4.0.3 on 2022-04-10 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimosoApp', '0002_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='phone',
            field=models.CharField(blank=True, default='+255', max_length=200, null=True),
        ),
    ]
