# Generated by Django 4.0.3 on 2022-04-18 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DimosoApp', '0012_cbgform6report_ecaform6report_hgkform6report_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcbform6students',
            name='darasa',
            field=models.ForeignKey(default='PCB', on_delete=django.db.models.deletion.CASCADE, to='DimosoApp.combination'),
        ),
    ]
